{{- if and .Values.minio.enabled (not .Values.minio.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opengeni.minioSecretName" . }}
  labels:
    {{- include "opengeni.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
stringData:
  {{ .Values.minio.auth.accessKeyKey }}: {{ .Values.minio.auth.rootUser | quote }}
  {{ .Values.minio.auth.secretKeyKey }}: {{ .Values.minio.auth.rootPassword | quote }}
{{- end }}
