export { OpenGeniClient } from "./client";
export type { FetchLike, OpenGeniClientOptions, SendMessageInput, SteerMessageResult } from "./client";
export { OpenGeniApiError, OpenGeniStreamError, isRetryableStreamError } from "./errors";
export {
  formatSseEvent,
  proxySessionEventStream,
  resumeSequenceFromRequest,
  sessionEventsToSseResponse,
  sessionEventsToSseStream,
} from "./proxy";
export type { ProxySessionEventStreamOptions, SseReStreamOptions } from "./proxy";
export { parseSseStream } from "./sse";
export type { SseMessage } from "./sse";
// Desktop (noVNC) transport contract — pure, zero-dep (the RFB import lives in
// @opengeni/react). URL assembler + connection state machine + rotation fence.
export { desktopSocketUrl, nextDesktopState, applyUrlRotation } from "./desktop";
export type {
  DesktopRfbLike,
  DesktopRfbFactory,
  DesktopConnectionState,
  DesktopStreamEvent,
} from "./desktop";
// Interactive terminal (ttyd PTY-over-websocket) transport contract — pure,
// zero-dep (the WebSocket + xterm attach live in @opengeni/react). URL assembler
// + the ttyd wire-protocol frame codec, symmetric with the desktop above.
export {
  terminalSocketUrl,
  ttydAuthFrame,
  ttydInputFrame,
  ttydResizeFrame,
  TTYD_SUBPROTOCOL,
  TtydClientCommand,
  TtydServerCommand,
} from "./terminal";
export { streamSessionEvents } from "./stream";
export type {
  SessionEventStreamTransport,
  StreamConnectionState,
  StreamSessionEventsOptions,
} from "./stream";
export { KNOWN_PERMISSIONS, KNOWN_USAGE_EVENT_TYPES, SESSION_EVENT_TYPES } from "./types";
export type {
  AccessContext,
  AccessGrant,
  AccountGrant,
  AccountRole,
  AddWorkspaceMemberRequest,
  AgentMessageCompletedPayload,
  AgentTextDeltaPayload,
  AgentToolCallCreatedPayload,
  AgentToolCallOutputPayload,
  ApiKey,
  BillingBalance,
  BillingEntitlementsResponse,
  BillingMode,
  BillingSummary,
  BillingUsageResponse,
  CapabilityCatalogItem,
  CapabilityCatalogResponse,
  CapabilityInstallation,
  CapabilityInstallationStatus,
  CapabilityKind,
  CapabilityPack,
  CapabilityPackConnector,
  CapabilityPackConnectorAuthModel,
  CapabilityPackEnvironmentSpec,
  CapabilityPackKnowledge,
  CapabilityPackScheduledTaskTemplate,
  CapabilityPackSkill,
  CapabilityPackSkillFile,
  CapabilityRuntime,
  CapabilitySource,
  CapabilityUnavailableReason,
  ClientConfig,
  ClientModel,
  CompactSessionContextResult,
  ClientSessionEventInput,
  CompleteFileUploadResponse,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
  CreateCapabilityCatalogItemRequest,
  CreateCheckoutRequest,
  CreateCheckoutResponse,
  CreateDocumentBaseRequest,
  CreateFileUploadRequest,
  CreateFileUploadResponse,
  CreateGitHubAppManifestRequest,
  CreateGitHubAppManifestResponse,
  CreateScheduledTaskRequest,
  CreateSessionRequest,
  CreateWorkspaceEnvironmentRequest,
  CreateWorkspaceRequest,
  DiscoverMcpCapabilitiesResponse,
  Document,
  DocumentBase,
  DocumentSearchRequest,
  DocumentSearchResponse,
  DocumentSearchResult,
  DocumentStatus,
  EnableCapabilityRequest,
  EnablePackRequest,
  Entitlements,
  EntitlementValue,
  EntitlementsMode,
  FileAsset,
  FileDownloadUrlResponse,
  FileResourceRef,
  FileStatus,
  FileUploadData,
  GetPackResponse,
  GitHubAppInfo,
  GitHubRepositoriesResponse,
  GitHubRepository,
  GoalSpec,
  KnownPermission,
  KnownSessionEventType,
  KnownUsageEventType,
  ListApiKeysResponse,
  ListPacksResponse,
  ListWorkspaceMembersResponse,
  PackInstallation,
  PackInstallationStatus,
  Permission,
  ProductAccessMode,
  ReasoningEffort,
  RecordingAvailablePayload,
  RecordingCodec,
  RecordingContentType,
  RecordingFailedPayload,
  RecordingFailedReason,
  RecordingMode,
  RecordingStartedPayload,
  RegisterCapabilityPackRequest,
  RepositoryResourceRef,
  ResourceRef,
  SandboxBackend,
  SandboxCapabilityName,
  SandboxOs,
  ScheduledTask,
  ScheduledTaskAgentConfig,
  ScheduledTaskAgentConfigInput,
  ScheduledTaskDayOfWeek,
  ScheduledTaskOverlapPolicy,
  ScheduledTaskRun,
  ScheduledTaskRunMode,
  ScheduledTaskRunStatus,
  ScheduledTaskScheduleSpec,
  ScheduledTaskStatus,
  ScheduledTaskTriggerType,
  Session,
  SessionCapabilities,
  // Per-surface capability cell aliases (views of SessionCapabilities).
  FileSystemCapability,
  TerminalCapability,
  GitCapability,
  DesktopStreamCapability,
  RecordingCapability,
  ComputerUseCapability,
  // Stream-surfacing client surface (Phase 5).
  ClientAuthConfig,
  StreamUrlRotatedPayload,
  StreamOpenedPayload,
  StreamClosedPayload,
  StreamRevokedPayload,
  AttachViewerRequest,
  AttachViewerResponse,
  ViewerHolder,
  AcknowledgeStreamRequest,
  AcknowledgeStreamResponse,
  ViewerHeartbeatRequest,
  ViewerHeartbeatResponse,
  SessionEvent,
  SessionEventType,
  SessionGoal,
  SessionGoalCreatedBy,
  SessionGoalStatus,
  SessionStatus,
  SessionStatusChangedPayload,
  SessionStructuredCapabilities,
  SessionTurn,
  SessionTurnSource,
  SessionTurnStatus,
  // Channel-A structured services (P4.4) — A1 payloads + A2 request/response.
  SandboxCommandOutputDeltaPayload,
  FsChangeKind,
  FsChangedPayload,
  GitChangedPayload,
  TerminalPtyStartedPayload,
  TerminalPtyOutputDeltaPayload,
  TerminalPtyExitedPayload,
  FsNodeType,
  FsTreeNode,
  FsEncoding,
  FsListRequest,
  FsListResponse,
  FsReadRequest,
  FsReadResponse,
  FsWriteRequest,
  FsWriteResponse,
  FsDeleteRequest,
  FsDeleteResponse,
  FsMoveRequest,
  FsMoveResponse,
  FsMkdirRequest,
  FsMkdirResponse,
  GitFileStatusCode,
  GitFileStatus,
  GitStatusRequest,
  GitStatusResponse,
  GitDiffLineType,
  GitDiffLine,
  GitDiffHunk,
  GitFileDiff,
  GitDiffRequest,
  GitDiffResponse,
  GitLogRequest,
  GitCommit,
  GitLogResponse,
  GitShowRequest,
  GitShowResponse,
  TerminalExecRequest,
  TerminalExecResponse,
  PtyOpenRequest,
  PtyOpenResponse,
  PtyWriteRequest,
  PtyResizeRequest,
  PtyCloseRequest,
  ToolRef,
  UpdateScheduledTaskRequest,
  UpdateSessionGoalRequest,
  UpdateSessionTurnRequest,
  UpdateWorkspaceEnvironmentRequest,
  UpdateWorkspaceMemberRequest,
  UpdateWorkspaceRequest,
  UploadFileInput,
  UsageEvent,
  UsageEventType,
  UserApprovalDecisionEventInput,
  UserInterruptEventInput,
  UserMessageEventInput,
  Workspace,
  WorkspaceEnvironment,
  WorkspaceEnvironmentVariableMetadata,
  WorkspaceMember,
  WorkspaceRegisteredPack,
} from "./types";
