import type { Settings } from "@opengeni/config";

export function testSettings(overrides: Partial<Settings> = {}): Settings {
  return {
    serviceName: "opengeni",
    environment: "test",
    deploymentRevision: "dev",
    databaseUrl: "postgres://opengeni:opengeni@127.0.0.1:5432/opengeni",
    natsUrl: "nats://127.0.0.1:4222",
    temporalHost: "127.0.0.1:7233",
    temporalNamespace: "default",
    temporalTaskQueue: `opengeni-test-${crypto.randomUUID()}`,
    startupDependencyRetryAttempts: 1,
    startupDependencyRetryInitialDelayMs: 1,
    startupDependencyRetryMaxDelayMs: 1,
    observabilityStructuredLogs: false,
    observabilityMetricsEnabled: true,
    observabilityOtlpEndpoint: undefined,
    observabilityOtlpHeaders: "",
    authRequired: false,
    accessKey: undefined,
    authAllowHealth: true,
    authAllowMetrics: false,
    publicBaseUrl: "http://127.0.0.1:3000",
    productAccessMode: "local",
    billingMode: "disabled",
    entitlementsMode: "none",
    usageLimitsMode: "none",
    staticEntitlementsJson: "{}",
    staticUsageLimitsJson: "{}",
    delegationSecret: "test-delegation-secret",
    environmentsEncryptionKey: undefined,
    goalMaxAutoContinuations: 20,
    goalNoProgressLimit: 3,
    betterAuthSecret: undefined,
    betterAuthAllowedHosts: "",
    betterAuthCookieDomain: undefined,
    betterAuthTrustedOrigins: "",
    resendApiKey: undefined,
    emailFrom: "OpenGeni <auth@mail.opengeni.ai>",
    stripeSecretKey: undefined,
    stripePublishableKey: undefined,
    stripeWebhookSecret: undefined,
    apiHost: "127.0.0.1",
    apiPort: 0,
    corsAllowOriginRegex: String.raw`https?://(localhost|127\.0\.0\.1)(:\d+)?`,
    openaiProvider: "openai",
    openaiApiKey: "test-openai-key",
    openaiBaseUrl: undefined,
    openaiModel: "scripted-model",
    openaiAllowedModels: "scripted-model,gpt-5.5,gpt-5.4,gpt-5.4-mini",
    modelPricingJson: JSON.stringify({
      "scripted-model": {
        inputMicrosPerMillionTokens: 0,
        outputMicrosPerMillionTokens: 0,
      },
      "gpt-5.5": {
        inputMicrosPerMillionTokens: 1,
        outputMicrosPerMillionTokens: 1,
      },
      "gpt-5.4": {
        inputMicrosPerMillionTokens: 1,
        outputMicrosPerMillionTokens: 1,
      },
      "gpt-5.4-mini": {
        inputMicrosPerMillionTokens: 1,
        outputMicrosPerMillionTokens: 1,
      },
    }),
    openaiReasoningEffort: "high",
    openaiAllowedReasoningEfforts: "low,medium,high,xhigh",
    openaiResponsesTransport: "http",
    azureOpenaiBaseUrl: undefined,
    azureOpenaiEndpoint: undefined,
    azureOpenaiDeployment: undefined,
    azureOpenaiApiVersion: undefined,
    azureOpenaiApiKey: undefined,
    azureOpenaiAdToken: undefined,
    disableOpenaiTracing: true,
    sandboxBackend: "none",
    dockerImage: "opengeni-sandbox:local",
    dockerExposedPorts: "",
    dockerNetwork: undefined,
    modalAppName: "opengeni-sandbox",
    modalImageRef: undefined,
    modalTimeoutSeconds: 900,
    modalTokenId: undefined,
    modalTokenSecret: undefined,
    modalEnvironment: undefined,
    sandboxPreparationProfiles: "none",
    sandboxEnvAllowlist: "",
    objectStorageEndpoint: undefined,
    objectStorageSandboxEndpoint: undefined,
    objectStorageBackend: "s3-compatible",
    objectStorageBucket: "opengeni-files",
    objectStorageRegion: "us-east-1",
    objectStorageS3Provider: "Minio",
    objectStorageAccessKeyId: undefined,
    objectStorageSecretAccessKey: undefined,
    objectStorageForcePathStyle: true,
    objectStorageAzureConnectionString: undefined,
    objectStorageAzureAccountName: undefined,
    objectStorageAzureAccountKey: undefined,
    objectStorageAzureEndpoint: undefined,
    documentParser: "liteparse",
    documentChunkSize: 1200,
    documentChunkOverlap: 160,
    documentEmbeddingProvider: "deterministic",
    documentEmbeddingModel: "deterministic-local-3072",
    documentEmbeddingDimensions: 3072,
    documentEmbeddingApiKey: undefined,
    documentEmbeddingBaseUrl: undefined,
    gitAuthorName: undefined,
    gitAuthorEmail: undefined,
    gitCommitterName: undefined,
    gitCommitterEmail: undefined,
    githubAppManifestBaseUrl: undefined,
    githubAppManifestStateSecret: "test-state-secret",
    githubAppId: undefined,
    githubClientId: undefined,
    githubClientSecret: undefined,
    githubAppSlug: undefined,
    githubWebhookSecret: undefined,
    githubAppPrivateKey: undefined,
    mcpServers: [],
    ...overrides,
  };
}
