interface Args {
  out: string | null;
}

const args = parseArgs(process.argv.slice(2));
const values = renderTemporalValues(process.env);

if (args.out) {
  await Bun.write(args.out, values);
} else {
  process.stdout.write(values);
}

export function renderTemporalValues(env: Record<string, string | undefined>): string {
  const host = env.TEMPORAL_POSTGRES_HOST?.trim();
  const port = env.TEMPORAL_POSTGRES_PORT?.trim() || "5432";
  const connectAddr = env.TEMPORAL_POSTGRES_CONNECT_ADDR?.trim() || (host ? `${host}:${port}` : "");
  if (!connectAddr) {
    throw new Error("TEMPORAL_POSTGRES_HOST or TEMPORAL_POSTGRES_CONNECT_ADDR is required");
  }
  const user = env.TEMPORAL_POSTGRES_USER?.trim() || "opengeni";
  const secretName = env.TEMPORAL_POSTGRES_SECRET_NAME?.trim() || "opengeni-temporal-postgres";
  const secretKey = env.TEMPORAL_POSTGRES_SECRET_KEY?.trim() || "password";
  const defaultDatabase = env.TEMPORAL_POSTGRES_DEFAULT_DATABASE?.trim() || "temporal";
  const visibilityDatabase = env.TEMPORAL_POSTGRES_VISIBILITY_DATABASE?.trim() || "temporal_visibility";
  const createDatabase = booleanEnv(env, "TEMPORAL_POSTGRES_CREATE_DATABASE", true);
  const shards = positiveIntegerEnv(env, "TEMPORAL_NUM_HISTORY_SHARDS", "128");
  const tlsEnabled = booleanEnv(env, "TEMPORAL_POSTGRES_TLS_ENABLED", false);
  const tlsCaFile = env.TEMPORAL_POSTGRES_TLS_CA_FILE?.trim();
  const tlsCaConfigMapName = env.TEMPORAL_POSTGRES_TLS_CA_CONFIG_MAP_NAME?.trim();
  const tlsCaConfigMapKey = env.TEMPORAL_POSTGRES_TLS_CA_CONFIG_MAP_KEY?.trim() || "ca.pem";
  const tlsCaMount = tlsCaFile && tlsCaConfigMapName
    ? renderCaMount("temporal-postgres-ca", tlsCaConfigMapName, tlsCaConfigMapKey, tlsCaFile)
    : "";
  const tlsYaml = tlsEnabled
    ? `\n            tls:\n              enabled: true${tlsCaFile ? `\n              caFile: ${yamlScalar(tlsCaFile)}` : ""}`
    : "";

  return `# Generated by scripts/deployment-temporal-values.ts. Do not commit generated copies.
server:
${tlsCaMount}  replicaCount: 1
  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      numHistoryShards: ${yamlScalar(shards)}
      datastores:
        default:
          sql:
            createDatabase: ${yamlScalar(String(createDatabase))}
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: ${yamlScalar(defaultDatabase)}
            connectAddr: ${yamlScalar(connectAddr)}
            connectProtocol: tcp
            user: ${yamlScalar(user)}
            existingSecret: ${yamlScalar(secretName)}
            secretKey: ${yamlScalar(secretKey)}
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: 1h${tlsYaml}
        visibility:
          sql:
            createDatabase: ${yamlScalar(String(createDatabase))}
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: ${yamlScalar(visibilityDatabase)}
            connectAddr: ${yamlScalar(connectAddr)}
            connectProtocol: tcp
            user: ${yamlScalar(user)}
            existingSecret: ${yamlScalar(secretName)}
            secretKey: ${yamlScalar(secretKey)}
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: 1h${tlsYaml}
  metrics:
    annotations:
      enabled: true

web:
  enabled: false

schema:
  useHelmHooks: true
  backoffLimit: 100
  ttlSecondsAfterFinished: 86400

${tlsCaMount ? `admintools:\n${tlsCaMount}` : ""}`;
}

function parseArgs(values: string[]): Args {
  const out: Args = { out: null };
  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];
    if (value === "--out") {
      const next = values[index + 1];
      if (!next) {
        throw new Error("--out requires a value");
      }
      out.out = next;
      index += 1;
      continue;
    }
    if (value.startsWith("--out=")) {
      out.out = value.slice("--out=".length);
      continue;
    }
    throw new Error(`Unknown argument: ${value}`);
  }
  return out;
}

function positiveIntegerEnv(env: Record<string, string | undefined>, name: string, fallback: string): string {
  const value = env[name]?.trim() || fallback;
  if (!/^[1-9][0-9]*$/.test(value)) {
    throw new Error(`${name} must be a positive integer`);
  }
  return value;
}

function booleanEnv(env: Record<string, string | undefined>, name: string, fallback: boolean): boolean {
  const raw = env[name]?.trim();
  if (!raw) return fallback;
  if (/^(1|true|yes)$/i.test(raw)) return true;
  if (/^(0|false|no)$/i.test(raw)) return false;
  throw new Error(`${name} must be true or false`);
}

function renderCaMount(volumeName: string, configMapName: string, configMapKey: string, mountPath: string): string {
  return `  additionalVolumes:
    - name: ${yamlScalar(volumeName)}
      configMap:
        name: ${yamlScalar(configMapName)}
        items:
          - key: ${yamlScalar(configMapKey)}
            path: ca.pem
  additionalVolumeMounts:
    - name: ${yamlScalar(volumeName)}
      mountPath: ${yamlScalar(mountPath)}
      subPath: ca.pem
      readOnly: true
`;
}

function yamlScalar(value: string): string {
  if (/^(true|false|[0-9]+)$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}
